export { BomberIcon } from './BomberIcon'
export { PantsIcon } from './PantsIcon'
export { ShoeIcon } from './ShoeIcon'
export { TShirtIcon } from './TShirtIcon'
export type { GarmentIconProps } from './GarmentIconFrame'
